version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://boopathid:Boopathi2001@boopathi.rjk1x.mongodb.net/upskill_global?authSource=admin&retryWrites=true&w=majority
      - JWT_SECRET=your_jwt_secret_key_here
