[phases.setup]
  aptPkgs = ["nodejs", "npm"]

[phases.install]
  cmds = [
    "npm install -g npm@latest",
    "npm install"
  ]

[phases.build]
  cmds = [
    "npm run build:frontend",
    "npm run build:backend"
  ]

[start]
  cmd = "npm run start:backend"

[variables]
  NODE_ENV = "production"
