name: Azure Static Web Apps CI/CD for my-upskill-global

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: false
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json
            backend/package-lock.json

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci --prefer-offline --no-audit

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build
        env:
          CI: false

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci --prefer-offline --no-audit

      - name: Validate Backend Environment
        working-directory: ./backend
        run: npm run validate-env
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}

      - name: Build Backend
        working-directory: ./backend
        run: npm run build
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Prune Backend Dependencies
        run: |
          cd backend
          npm prune --production
          du -sh node_modules

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MY_UPSKILL_GLOBAL }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./frontend"
          api_location: "./backend"
          output_location: "build"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MY_UPSKILL_GLOBAL }}
          action: "close"
